spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/oson_sot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
logging:
  file:
    name: logback
telegram:
  api-url: "https://api.telegram.org/"
  webhook-path: "https://057e-89-146-124-119.eu.ngrok.io"
  bot-token: 5477032442:AAECQriDE71D-kRzgFAaqrae1GMeyP7mEMU
  bot-name: osonsot_bot
server:
  port: 90
