spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    password: 123
    username: postgres
    url: jdbc:postgresql://localhost:5432/oson_sot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
logging:
  file:
    name: logback